AWSTemplateFormatVersion: '2010-09-09'
Description: Web Stack

Parameters:
  KnowledgeBaseId:
    Type: String
    Description: The ID of the Knowledge Base

Resources:

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AdministratorAccess'

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: defaultVpc

  chatbotAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http and ssh traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC

  chatbotAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Sub 'ami-${/aws/service/canonical/ubuntu/server/focal/stable/current/amd64/hvm/ebs-gp2/ami-id}'
      InstanceType: m5.large
      IamInstanceProfile: !Ref InstanceRole
      SecurityGroupIds:
        - !Ref chatbotAppSecurityGroup
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash

            # Update packages
            sudo apt-get update -y

            # Install required packages
            sudo apt-get install -y ec2-instance-connect
            sudo apt-get install -y git
            sudo apt-get install -y python3-pip
            sudo apt-get install -y python3.8-venv

            # Clone repository
            cd /home/ubuntu
            sudo git clone https://github.com/ottlseo/bedrock-rag-chatbot.git

            # Create virtual environment
            sudo python3 -m venv --copies /home/ubuntu/my_env
            sudo chown -R ubuntu:ubuntu /home/ubuntu/my_env
            source /home/ubuntu/my_env/bin/activate

            cd bedrock-rag-chatbot

            # Install dependencies
            pip3 install -r requirements.txt

            # Create systemd service
            sudo sh -c "cat <<EOF > /etc/systemd/system/streamlit.service
            [Unit]
            Description=Streamlit App
            After=network.target

            [Service]
            User=ubuntu
            Environment='AWS_DEFAULT_REGION=us-west-2'
            WorkingDirectory=/home/ubuntu/bedrock-rag-chatbot
            ExecStartPre=/bin/bash -c 'sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8501'
            ExecStart=/bin/bash -c 'source /home/ubuntu/my_env/bin/activate && streamlit run streamlit.py --server.port 8501'
            Restart=always

            [Install]
            WantedBy=multi-user.target
            EOF"

            # Reload systemd daemon and start the service
            sudo systemctl daemon-reload
            sudo systemctl enable streamlit
            sudo systemctl start streamlit

  KnowledgeBaseIdParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /RAGChatBot/KNOWLEDGE_BASE_ID
      Type: String
      Value: !Ref KnowledgeBaseId

  chatbotAppUrl:
    Type: AWS::CloudFormation::Output
    Value: !Sub 'http://${chatbotAppInstance.PublicIpAddress}/'
    Description: '[PLEASE CONNECT IN 5 MINUTES] The URL of chatbot demo generated by AWS RAG-Made-Easy project'
    Export:
      Name: chatbotAppUrl